application: quora-jz1371 # project-id on google engine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: quora.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
