application: quora-jz1371 # project-id on google engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

# add local external js library
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images
  
- url: /.*
  script: main.app
#  script: quora.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
